services:
  - type: web
    name: devlynix-backend
    env: docker
    plan: free
    envVars:
      - key: PGHOST
        sync: false
      - key: PGPORT
        value: 5432
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: SQL_INIT_MODE
        value: always
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_ORIGINS
        sync: false
